name: Run tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: |
          11
          17
        distribution: 'temurin'
    - name: Run tests
      run: mvn --batch-mode test
    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and analyze
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: >-
        mvn --batch-mode verify sonar:sonar
        -Dsonar.java.jdkHome=$JAVA_HOME_11_X64
        -Dsonar.projectKey=pgmarc_space-java-client
        -Pcoverage
